ENTER_COOKING_TIME = 'Время приготовления'
ENTER_DESCRIPTION = 'Описание'
ENTER_HEX = 'HEX-код цвета'
ENTER_IMAGE = 'Изображение'
ENTER_INGREDIENT_NAME = 'Название ингредиента'
ENTER_QUANTITY_INGREDIENTS = 'Количество ингредиентов'
ENTER_SLUG = 'Slug'
ENTER_TAG = 'Название тега'
ENTER_TIME_CREATION = 'Дата и время создания'
ENTER_UNIT = 'Единица измерения'

MAX_LENGTH_INGREDIENT_NAME = 200
MAX_LENGTH_INGREDIENT_UNIT = 20
MAX_LENGTH_RECIPE_NAME = 200
MAX_LENGTH_TAG_COLOR = 7
MAX_LENGTH_TAG_NAME = 22
MAX_LENGTH_TAG_SLUG = 200
MAX_VALUE_COOKING_TIME = 4320
MIN_VALUE_COOKING_TIME = 1

PAGE_SIZE = 6
